name: <a href="https://github.com/poslegm" target="_blank">GITHUB</a> | <a href="https://t.me/lilfunctor" target="_blank">TLGRM</a> | <a href="https://www.linkedin.com/in/poslegm/" target="_blank">LINKEDIN</a>
meta_description: "Михаил Чугунков"

markdown: kramdown
highlighter: pygments
paginate: 10
baseurl: /blog
domain_name: "https://chugunkov.dev"
url: "https://chugunkov.dev/blog"
google_analytics: "UA-73475101-2"
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-gzip]
sass:
    sass_dir: _sass
    style: compressed

# Details for the RSS feed generator
rss_url: "https://chugunkov.dev/blog"
author: "Михаил Чугунков"
