name: <a href="/">Главная</a>
meta_description: "Михаил Чугунков"

markdown: kramdown
highlighter: pygments
paginate: 10
baseurl: /
domain_name: "https://chugunkov.dev"
url: "https://chugunkov.dev/"
google_analytics: "UA-73475101-2"
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-gzip]
paginate_path: "/blog/page:num/"
sass:
    sass_dir: _sass
    style: compressed

# Details for the RSS feed generator
rss_url: "https://chugunkov.dev/"
author: "Михаил Чугунков"
